### ISSUE TITLE
400 on GET objects/[object]

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleViewer#37]
e.g. when URL is `http://104.131.39.3:8080/?server=http://104.131.39.3:3000`  we get the error `GET http://104.131.39.3:3000/api/v1/objects/5a7b1acc6834136c23c73ea0?omit=base64,rawData 400 (Bad Request)`

User login & stream lists work as expected

**Comment by mswaidan** [comment]
Server error:

```
2018-04-03T02:15:32.769Z - info: HTTP GET /api/v1/objects/5a7b1acc6834136c23c73ea0 400
debug: checking perms false | guest |
error:  TypeError: Cannot read property 'toString' of undefined
    at Promise (/root/SpeckleServer/app/api/v1/middleware/PermissionCheck.js:20:75)
    at new Promise (<anonymous>)
    at module.exports (/root/SpeckleServer/app/api/v1/middleware/PermissionCheck.js:12:10)
    at SpeckleObject.findOne.then.object (/root/SpeckleServer/app/api/v1/objects/ObjectGet.js:16:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```

**Comment by mswaidan** [comment]
Objects created on old api don't have 'owner' property, so perm check fails.

**Comment by didimitrie** [comment]
Yes, i'm afraid this is not gonna be backwards compatible unless i introduce a big risky thing (treat resources with no owner as public)
